### ISSUE TITLE
javax.persistence.TransactionRequiredException: no transaction is in progress

### ISSUE THREAD

**Issue by petrosbaltzis** [symentis/grails-audit-logging-plugin#175]
I am getting the exception above when I try to save an auditable domain.
Grails version: 3.3.2
Grails-audit-logging-plugin version: 3.0.1

On the service level, I use the @Transactional annotation, therefore, in theory, there is an open transaction. 
I have tried to use different propagations (REQUIRED, REQUIRED_NEW) but I got the same exception.

I wonder if it is something wrong in my configuration or if it is a potential bug.

**Comment by robertoschwald** [comment]
Should work. See #161

**Comment by longwa** [comment]
The events aren't within the existing transaction as they are triggered as part of the flush itself. The solution is to use the same approach as hibernate-envers, which is to register a callback which is executed on transaction commit to write the entries. This is a requirement for the plugin to work correctly in Grails 4.0 as it requires Hibernate 5.4+.

I'm working on a fix.

**Comment by luke10** [comment]
Just to add my 2c, I'm also blocked by this issue as I am using a more recent version of Hibernate for other purposes. For now, I've avoided the issue by setting `hibernate.allow_update_outside_transaction = true` but this must never make it to production..

**Comment by wkulik** [comment]
I also have the allow update outside transaction set to true for now. I am currently using Grails 3.3. Are there any updates upcoming or suggested workarounds that can be used in a Production environment, or should I use a different auditing method?

**Comment by robertoschwald** [comment]
We are working on the tests for longwa's approach. See branch [4.0.0_wip](https://github.com/robertoschwald/grails-audit-logging-plugin/tree/feature/4.0.0_wip)

**Comment by nitinmahawadiwar** [comment]
I am able to fix the issue as commented by @luke10 , but then what should be ideal solution for Production environment.

**Comment by robertoschwald** [comment]
As we are not ready with the new approach, yet, we use a workaround which spawns own transaction. Give release 3.0.6 a try.
