### ISSUE TITLE
Link for User Guide is not working

### ISSUE THREAD

**Issue by madasaca29** [symentis/grails-audit-logging-plugin#216]
I'm sorry, I don't know where put this, but the link for the user guide is not working, can you help me?

![imagen](https://user-images.githubusercontent.com/9580154/115625091-cce25800-a2b8-11eb-9866-258af51f29a9.png)

**Comment by robertoschwald** [comment]
We've started preparing the Bintray to Maven Central migration. Due to this, we moved the repo into our organization yesterday. 

The link is now https://symentis.github.io/grails-audit-logging-plugin/

Sorry for the confusion. Will be fixed automatically with the next deployment.
