### ISSUE TITLE
oldValue is always showing up as N/A for Persistent List

### ISSUE THREAD

**Issue by wrvenkatesh** [symentis/grails-audit-logging-plugin#231]
Hi

I have a domain object with List as one of the attributes. When using the plugin and making updates to the domain object, I am noticing that the oldValue for the List always shows up as `N/A` while the newValue shows comma separated values. How do I make the oldValue show the actual values instead of what I see.

For instance

class Employee {
   String name;
   List mobileNumbers; // this is one to many
}

Expected Behavior:

oldValue should show comma separated values.

Actual Behavior: 

What I see in the audit table is just N/A for the oldValue column. I did some debugging and found getOriginalValue function in AuditLogListenerUtil is setting this. I couldnt find a way to override this behavior

Environment Information

- **Operating System**: Windows
- **GORM Version:** 
- **Grails Version (if using Grails):** 4.0.10
- **JDK Version:** Java 8

Thanks
Venkatesh

**Comment by robertoschwald** [comment]
Unfortunately, we didn't find a way to get the oldValue on collections.

**Comment by wrvenkatesh** [comment]
Ahh, I was hoping for a solution :-). But thanks so much for the quick revert. I will go ahead and close the Issue for now?
